[PHP]
memory_limit = 256M
upload_max_filesize = 64M
post_max_size = 64M
max_execution_time = 300
display_errors = On
display_startup_errors = On
error_reporting = E_ALL

; [PHP]
; memory_limit = 128M
; upload_max_filesize = 16M
; post_max_size = 16M
; max_execution_time = 60
; display_errors = Off
; display_startup_errors = Off
; error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT