/**
 * GitHub Webhook Handler
 * 
 * Process incoming webhook events from GitHub:
 * - PR opened/updated/closed
 * - Push events
 * - Check suite completed
 */

import { handleWebhookEvent, GitHubConfig, WebhookPayload } from './pr-creator';

interface WebhookHandlerConfig {
  github: GitHubConfig;
  onPROpened?: (pr: Record<string, unknown>) => Promise<void>;
  onPRMerged?: (pr: Record<string, unknown>) => Promise<void>;
  onPRClosed?: (pr: Record<string, unknown>) => Promise<void>;
  onPRUpdated?: (pr: Record<string, unknown>) => Promise<void>;
  onPush?: (payload: Record<string, unknown>) => Promise<void>;
}

/**
 * Process a webhook payload
 */
export async function processWebhook(
  config: WebhookHandlerConfig,
  payload: WebhookPayload,
  event: string
): Promise<void> {
  const action = handleWebhookEvent(payload);
  
  switch (action.type) {
    case 'pr_opened':
      await config.onPROpened?.(action.pr!);
      break;
    case 'pr_merged':
      await config.onPRMerged?.(action.pr!);
      break;
    case 'pr_closed':
      await config.onPRClosed?.(action.pr!);
      break;
    case 'pr_updated':
      await config.onPRUpdated?.(action.pr!);
      break;
  }
  
  if (event === 'push' && payload) {
    await config.onPush?.(payload as Record<string, unknown>);
  }
}

/**
 * Generate PR template for a feature
 */
export function generatePRTemplate(
  type: 'feature' | 'bugfix' | 'hotfix' | 'refactor',
  title: string,
  description: string,
  relatedIssue?: number
): string {
  const typeEmoji = {
    feature: '✨',
    bugfix: '🐛',
    hotfix: '🔥',
    refactor: '♻️',
  }[type];
  
  return `## ${typeEmoji} ${title}

### Description
${description}

${relatedIssue ? `### Related Issue\nFixes #${relatedIssue}\n` : ''}

### Type of Change
- [ ] ${type === 'feature' ? '[x]' : '[ ]'} New feature
- [ ] ${type === 'bugfix' ? '[x]' : '[ ]'} Bug fix
- [ ] ${type === 'hotfix' ? '[x]' : '[ ]'} Hot fix
- [ ] ${type === 'refactor' ? '[x]' : '[ ]'} Refactoring

### Testing
- [ ] Unit tests pass
- [ ] Feature tests pass
- [ ] Manual testing completed

### Checklist
- [ ] Code follows Laravel Pint standards
- [ ] No N+1 queries
- [ ] CSRF tokens on all forms
- [ ] Swagger documentation updated (if API changes)
- [ ] .env.example updated (if new env vars)

---
*Generated by OpenCode*`;
}
